[project]
name = "rlx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium>=1.2.1",
    "mlx[cpu]>=0.29.2",
    "stable-baselines3>=2.7.0",
    "tensorboard>=2.20.0",
    "tyro>=0.9.32",
    "wandb>=0.22.2",
]
